CREATE TABLE cars.carreview
(
    ID BIGINT NOT NULL PRIMARY KEY,
    RATING INTEGER NOT NULL,
    REVIEW VARCHAR(500) NOT NULL,
    CAR_ID BIGINT NOT NULL REFERENCES cars.car(ID),
    USER_ID BIGINT NOT NULL REFERENCES cars.app_user(ID)
);

CREATE SEQUENCE cars.review_seq_gen
    INCREMENT 1
    START 1000;
